name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name : provide permission 
      run : chmod +x ./gradlew  
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: upload build to App Center
      uses: wzieba/AppCenter-Github-Action@v1.0.0
      with:
          appName: karishmathigale-gmail.com/GitHubActionDemo
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Collaborators
          file: app/build/outputs/apk/debug/app-debug.apk
  
    
