name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
       with:
        java-version: 1.8
    - name : jhgh
      run : chmod +x ./gradlew  
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      uses: wzieba/AppCenter-Github-Action@v1.0.0
      - name: upload build to App Center
        with:
          appName: wzieba/Demo-app
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Testers
          file: app/build/outputs/apk/debug/app-debug.apk
    
